SCHEMA orapcm

PUBLIC TYPE PCMB030M RECORD
    COIL_NO LIKE PCMB030M.COIL_NO,
    SCHD_NO LIKE PCMB030M.SCHD_NO,
    STATION LIKE PCMB030M.STATION,
    STATION_INDEX LIKE PCMB030M.STATION_INDEX,
    ACTL_STATION_CODE LIKE PCMB030M.ACTL_STATION_CODE,
    LAST_PROD_DATE LIKE PCMB030M.LAST_PROD_DATE,
    STEEL_GRADE LIKE PCMB030M.STEEL_GRADE,
    DIVIDE_YN LIKE PCMB030M.DIVIDE_YN,
    COIL_THICK LIKE PCMB030M.COIL_THICK,
    COIL_WIDTH LIKE PCMB030M.COIL_WIDTH,
    COIL_WEIGHT LIKE PCMB030M.COIL_WEIGHT,
    COIL_IN_DIAM LIKE PCMB030M.COIL_IN_DIAM,
    COIL_OUT_DIAM LIKE PCMB030M.COIL_OUT_DIAM,
    IC_CODE LIKE PCMB030M.IC_CODE,
    CLASS_CODE LIKE PCMB030M.CLASS_CODE,
    SURFACE_QUALITY LIKE PCMB030M.SURFACE_QUALITY,
    DEFACT01 LIKE PCMB030M.DEFACT01,
    DEFACT02 LIKE PCMB030M.DEFACT02,
    DEFACT03 LIKE PCMB030M.DEFACT03,
    DEFACT04 LIKE PCMB030M.DEFACT04,
    DEFACT05 LIKE PCMB030M.DEFACT05,
    ORDER_1 LIKE PCMB030M.ORDER_1,
    ORDER_2 LIKE PCMB030M.ORDER_2,
    ORDER_3 LIKE PCMB030M.ORDER_3,
    ORDER_4 LIKE PCMB030M.ORDER_4,
    ORDER_5 LIKE PCMB030M.ORDER_5,
    UAP_1 LIKE PCMB030M.UAP_1,
    UAP_2 LIKE PCMB030M.UAP_2,
    UAP_3 LIKE PCMB030M.UAP_3,
    UAP_4 LIKE PCMB030M.UAP_4,
    UAP_5 LIKE PCMB030M.UAP_5,
    HEAT_NO LIKE PCMB030M.HEAT_NO,
    DATE_LAST_MAINT LIKE PCMB030M.DATE_LAST_MAINT,
    TIME_LAST_MAINT LIKE PCMB030M.TIME_LAST_MAINT,
    PROG_LAST_MAINT LIKE PCMB030M.PROG_LAST_MAINT,
    USER_LAST_MAINT LIKE PCMB030M.USER_LAST_MAINT,
    STATION_CODE LIKE PCMB030M.STATION_CODE,
    EDGING LIKE PCMB030M.EDGING,
    OEM_NO LIKE PCMB030M.OEM_NO,
    MIC_NO LIKE PCMB030M.MIC_NO,
    NEXT_STATION LIKE PCMB030M.NEXT_STATION,
    PREV_STATION LIKE PCMB030M.PREV_STATION,
    LINE_MARKING LIKE PCMB030M.LINE_MARKING,
    SLEEVE_KIND LIKE PCMB030M.SLEEVE_KIND,
    PAPER_CODE LIKE PCMB030M.PAPER_CODE,
    MOTHER_COIL_NO LIKE PCMB030M.MOTHER_COIL_NO,
    SLAB_ID LIKE PCMB030M.SLAB_ID,
    PREV_SCHD_NO LIKE PCMB030M.PREV_SCHD_NO,
    OPER_CODE LIKE PCMB030M.OPER_CODE,
    OEM_LINE LIKE PCMB030M.OEM_LINE,
    SHIFT_DATE LIKE PCMB030M.SHIFT_DATE
END RECORD

########################################################

#-------------------------------------------------------
# init. For Dependency Diagram Tracing
#-------------------------------------------------------
FUNCTION init_PCMB030M()
END FUNCTION

########################################################

PUBLIC FUNCTION (src_rec PCMB030M) getByHSM(arg_coil LIKE PCMB030M.coil_no)
    DEFINE mother_coil CHAR(11)
    DEFINE s_tmp STRING
    
    LET s_tmp = arg_coil
    LET mother_coil = s_tmp.subString(1,8)
    
    SELECT CLASS_CODE, COIL_THICK INTO src_rec.class_code, src_rec.coil_thick
    FROM pcmb030m
    WHERE STATION = 'HSM' AND COIL_NO = mother_coil

    IF SQLCA.SQLERRD[2] != "0" THEN
        SELECT CLASS_CODE, COIL_THICK INTO src_rec.class_code, src_rec.coil_thick
        FROM pcmb030m
        WHERE STATION = 'HSM' AND COIL_NO = arg_coil
    END IF
    
END FUNCTION