SCHEMA orapcm

PUBLIC TYPE PCMB100M RECORD
    ORDER_NO LIKE PCMB100M.ORDER_NO,
    ORDER_ITEM LIKE PCMB100M.ORDER_ITEM,
    ORDER_CUST_NO LIKE PCMB100M.ORDER_CUST_NO,
    ORDER_KIND LIKE PCMB100M.ORDER_KIND,
    PRODUCT_CODE LIKE PCMB100M.PRODUCT_CODE,
    SPEC LIKE PCMB100M.SPEC,
    STEEL_CODE LIKE PCMB100M.STEEL_CODE,
    MIC_NO LIKE PCMB100M.MIC_NO,
    PROCESS_CODE LIKE PCMB100M.PROCESS_CODE,
    STEEL_GRADE LIKE PCMB100M.STEEL_GRADE,
    PSR_NO LIKE PCMB100M.PSR_NO,
    APN_NO LIKE PCMB100M.APN_NO,
    TAR_THICK_CODE LIKE PCMB100M.TAR_THICK_CODE,
    ORDER_THICK LIKE PCMB100M.ORDER_THICK,
    ORDER_WIDTH LIKE PCMB100M.ORDER_WIDTH,
    ORDER_LENGTH LIKE PCMB100M.ORDER_LENGTH,
    ORDER_WEIGHT LIKE PCMB100M.ORDER_WEIGHT,
    DELIVERY_DATE LIKE PCMB100M.DELIVERY_DATE,
    ORDER_STATUS LIKE PCMB100M.ORDER_STATUS,
    ORDER_CHANGE LIKE PCMB100M.ORDER_CHANGE,
    ORDER_HURRY_CODE LIKE PCMB100M.ORDER_HURRY_CODE,
    TOL_WEIGHT_MAX LIKE PCMB100M.TOL_WEIGHT_MAX,
    TOL_WEIGHT_MIN LIKE PCMB100M.TOL_WEIGHT_MIN,
    UNIT_WEIGHT_MAX LIKE PCMB100M.UNIT_WEIGHT_MAX,
    UNIT_WEIGHT_MIN LIKE PCMB100M.UNIT_WEIGHT_MIN,
    COIL_IN_DIAM LIKE PCMB100M.COIL_IN_DIAM,
    COIL_OUT_DIAM_MAX LIKE PCMB100M.COIL_OUT_DIAM_MAX,
    SOLDER_CODE LIKE PCMB100M.SOLDER_CODE,
    EDGING LIKE PCMB100M.EDGING,
    SLEEVE_CODE LIKE PCMB100M.SLEEVE_CODE,
    MPL_MARK_CODE LIKE PCMB100M.MPL_MARK_CODE,
    MPL_PACK_CODE LIKE PCMB100M.MPL_PACK_CODE,
    MPL_LOAD_CODE LIKE PCMB100M.MPL_LOAD_CODE,
    DATE_LAST_MAINT LIKE PCMB100M.DATE_LAST_MAINT,
    TIME_LAST_MAINT LIKE PCMB100M.TIME_LAST_MAINT,
    PROG_LAST_MAINT LIKE PCMB100M.PROG_LAST_MAINT,
    USER_LAST_MAINT LIKE PCMB100M.USER_LAST_MAINT,
    ORDER_THICK_MAX LIKE PCMB100M.ORDER_THICK_MAX,
    ORDER_THICK_MIN LIKE PCMB100M.ORDER_THICK_MIN,
    ORDER_THICK_AIM LIKE PCMB100M.ORDER_THICK_AIM,
    ORDER_WIDTH_MAX LIKE PCMB100M.ORDER_WIDTH_MAX,
    ORDER_WIDTH_MIN LIKE PCMB100M.ORDER_WIDTH_MIN,
    APL_ROUTE LIKE PCMB100M.APL_ROUTE,
    CUT_LENGTH LIKE PCMB100M.CUT_LENGTH
END RECORD

########################################################

#-------------------------------------------------------
# init. For Dependency Diagram Tracing
#-------------------------------------------------------
FUNCTION init_PCMB100M()
END FUNCTION

########################################################

FUNCTION (src_rec PCMB100M) getPCMB100M()
    DEFINE order_no_tmp, order_item_tmp STRING
    
    SET CONNECTION "PCM"
    SELECT * INTO src_rec.* FROM PCMB100M
        WHERE ORDER_NO = src_rec.ORDER_NO
            AND ORDER_ITEM = src_rec.ORDER_ITEM

    IF SQLCA.sqlcode == 100 THEN
        LET order_no_tmp = src_rec.ORDER_NO
        LET order_item_tmp = src_rec.ORDER_ITEM
        INITIALIZE src_rec.* TO NULL
        LET src_rec.ORDER_NO = order_no_tmp
        LET src_rec.ORDER_ITEM = order_item_tmp
    END IF
END FUNCTION