SCHEMA orawip

PUBLIC TYPE WIPY020M RECORD
    COIL_NO LIKE WIPY020M.COIL_NO,
    OLD_YRD LIKE WIPY020M.OLD_YRD,
    STORAGE_LOCA LIKE WIPY020M.STORAGE_LOCA,
    DATE_LAST_MAINT LIKE WIPY020M.DATE_LAST_MAINT,
    TIME_LAST_MAINT LIKE WIPY020M.TIME_LAST_MAINT,
    USER_LAST_MAINT LIKE WIPY020M.USER_LAST_MAINT,
    PROG_LAST_MAINT LIKE WIPY020M.PROG_LAST_MAINT,
    SHIFT_NO LIKE WIPY020M.SHIFT_NO,
    MOVE_FLAG LIKE WIPY020M.MOVE_FLAG,
    STATION_CODE LIKE WIPY020M.STATION_CODE,
    COIL_PD LIKE WIPY020M.COIL_PD,
    COIL_WT LIKE WIPY020M.COIL_WT,
    COIL_WD LIKE WIPY020M.COIL_WD,
    COIL_TK LIKE WIPY020M.COIL_TK,
    WD_KIND LIKE WIPY020M.WD_KIND
END RECORD