SCHEMA orapcm

#------------------------------------------------------------------------------
# PCMB020M - PDI Part
#------------------------------------------------------------------------------
PUBLIC TYPE PCMB020M RECORD
    COIL_NO LIKE PCMB020M.COIL_NO,
    SLAB_ID LIKE PCMB020M.SLAB_ID,
    STEEL_GRADE LIKE PCMB020M.STEEL_GRADE,
    STEEL_KIND LIKE PCMB020M.STEEL_KIND,
    SERIAL_CODE LIKE PCMB020M.SERIAL_CODE,
    COIL_THICK LIKE PCMB020M.COIL_THICK,
    COIL_WIDTH LIKE PCMB020M.COIL_WIDTH,
    COIL_WEIGHT LIKE PCMB020M.COIL_WEIGHT,
    COIL_IN_DIAM LIKE PCMB020M.COIL_IN_DIAM,
    COIL_OUT_DIAM LIKE PCMB020M.COIL_OUT_DIAM,
    CLASS_CODE LIKE PCMB020M.CLASS_CODE,
    STORAGE_AREA LIKE PCMB020M.STORAGE_AREA,
    IC_CODE LIKE PCMB020M.IC_CODE,
    PLAN_PROC_CODE LIKE PCMB020M.PLAN_PROC_CODE,
    ACTL_STATION_CODE LIKE PCMB020M.ACTL_STATION_CODE,
    CURR_STATION_CODE LIKE PCMB020M.CURR_STATION_CODE,
    CURR_STATION_INDEX LIKE PCMB020M.CURR_STATION_INDEX,
    PLAN_MIC_NO LIKE PCMB020M.PLAN_MIC_NO,
    ACTL_MIC_NO LIKE PCMB020M.ACTL_MIC_NO,
    PREV_STATION LIKE PCMB020M.PREV_STATION,
    CURR_STATION LIKE PCMB020M.CURR_STATION,
    NEXT_STATION LIKE PCMB020M.NEXT_STATION,
    ROLLING_WEEK LIKE PCMB020M.ROLLING_WEEK,
    LAST_PROD_DATE LIKE PCMB020M.LAST_PROD_DATE,
    NO_OF_COIL LIKE PCMB020M.NO_OF_COIL,
    DEVIDE_STATION LIKE PCMB020M.DEVIDE_STATION,
    CB_FIRST_ORDER_ITEM LIKE PCMB020M.CB_FIRST_ORDER_ITEM,
    ORDER_WIDTH LIKE PCMB020M.ORDER_WIDTH,
    ORDER_THICK LIKE PCMB020M.ORDER_THICK,
    ORDER_IN_DIAM LIKE PCMB020M.ORDER_IN_DIAM,
    VENDOR_NO LIKE PCMB020M.VENDOR_NO,
    DEFACT01 LIKE PCMB020M.DEFACT01,
    DEFACT02 LIKE PCMB020M.DEFACT02,
    DEFACT03 LIKE PCMB020M.DEFACT03,
    DEFACT04 LIKE PCMB020M.DEFACT04,
    DEFACT05 LIKE PCMB020M.DEFACT05,
    DATE_LAST_MAINT LIKE PCMB020M.DATE_LAST_MAINT,
    TIME_LAST_MAINT LIKE PCMB020M.TIME_LAST_MAINT,
    PROG_LAST_MAINT LIKE PCMB020M.PROG_LAST_MAINT,
    USER_LAST_MAINT LIKE PCMB020M.USER_LAST_MAINT,
    HEAT_NO LIKE PCMB020M.HEAT_NO,
    SURFACE_QUALITY LIKE PCMB020M.SURFACE_QUALITY,
    EDGING LIKE PCMB020M.EDGING,
    OEM_NO LIKE PCMB020M.OEM_NO,
    LINE_MARKING LIKE PCMB020M.LINE_MARKING,
    SLEEVE_KIND LIKE PCMB020M.SLEEVE_KIND,
    PAPER_CODE LIKE PCMB020M.PAPER_CODE,
    MOTHER_COIL_NO LIKE PCMB020M.MOTHER_COIL_NO,
    PREV_SCHD_NO LIKE PCMB020M.PREV_SCHD_NO,
    OPER_CODE LIKE PCMB020M.OPER_CODE,
    RUSH_ORDER LIKE PCMB020M.RUSH_ORDER,
    COIL_APPLY LIKE PCMB020M.COIL_APPLY,
    CC_FLAG LIKE PCMB020M.CC_FLAG,
    COIL_LENGTH LIKE PCMB020M.COIL_LENGTH,
    PRODUCT_CODE LIKE PCMB020M.PRODUCT_CODE,
    QC_COMMENT LIKE PCMB020M.QC_COMMENT,
    FACTORY LIKE PCMB020M.FACTORY,
    TOTAL_REDUCTION LIKE PCMB020M.TOTAL_REDUCTION,
    RESTRICT_APN LIKE PCMB020M.RESTRICT_APN,
    FORECAST_DATE LIKE PCMB020M.FORECAST_DATE,
    AVAILABLE LIKE PCMB020M.AVAILABLE,
    SUB_COIL_WEIGHT LIKE PCMB020M.SUB_COIL_WEIGHT
END RECORD

########################################################

#-------------------------------------------------------
# init. For Dependency Diagram Tracing
#-------------------------------------------------------
FUNCTION init_PCMB020M()
END FUNCTION

########################################################

#------------------------------------------------------------------------------
# PDI req. data from PCMB020M
#------------------------------------------------------------------------------
FUNCTION (src_rec PCMB020M) getByCoilNo(arg_coil LIKE PCMB020M.coil_no)
    DEFINE data PCMB020M
    
    SET CONNECTION "PCM"
    
    SELECT *
        INTO data.*
        FROM pcmb020m
        WHERE COIL_NO = arg_coil

    LET src_rec.* = data.*
END FUNCTION

#------------------------------------------------------------------------------
#  update PCMB020M
#------------------------------------------------------------------------------
FUNCTION (src_rec PCMB020M) upd()
    SET CONNECTION "PCM"
    
    UPDATE PCMB020M SET
        SLAB_ID = NVL(src_rec.SLAB_ID,SLAB_ID),
        STEEL_GRADE = NVL(src_rec.STEEL_GRADE,STEEL_GRADE),
        STEEL_KIND = NVL(src_rec.STEEL_KIND,STEEL_KIND),
        SERIAL_CODE = NVL(src_rec.SERIAL_CODE,SERIAL_CODE),
        COIL_THICK = NVL(src_rec.COIL_THICK,COIL_THICK),
        COIL_WIDTH = NVL(src_rec.COIL_WIDTH,COIL_WIDTH),
        COIL_WEIGHT = NVL(src_rec.COIL_WEIGHT,COIL_WEIGHT),
        COIL_IN_DIAM = NVL(src_rec.COIL_IN_DIAM,COIL_IN_DIAM),
        COIL_OUT_DIAM = NVL(src_rec.COIL_OUT_DIAM,COIL_OUT_DIAM),
        CLASS_CODE = NVL(src_rec.CLASS_CODE,CLASS_CODE),
        STORAGE_AREA = NVL(src_rec.STORAGE_AREA,STORAGE_AREA),
        IC_CODE = NVL(src_rec.IC_CODE,IC_CODE),
        PLAN_PROC_CODE = NVL(src_rec.PLAN_PROC_CODE,PLAN_PROC_CODE),
        ACTL_STATION_CODE = NVL(src_rec.ACTL_STATION_CODE,ACTL_STATION_CODE),
        CURR_STATION_CODE = NVL(src_rec.CURR_STATION_CODE,CURR_STATION_CODE),
        CURR_STATION_INDEX = NVL(src_rec.CURR_STATION_INDEX,CURR_STATION_INDEX),
        PLAN_MIC_NO = NVL(src_rec.PLAN_MIC_NO,PLAN_MIC_NO),
        ACTL_MIC_NO = NVL(src_rec.ACTL_MIC_NO,ACTL_MIC_NO),
        PREV_STATION = NVL(src_rec.PREV_STATION,PREV_STATION),
        CURR_STATION = NVL(src_rec.CURR_STATION,CURR_STATION),
        NEXT_STATION = NVL(src_rec.NEXT_STATION,NEXT_STATION),
        ROLLING_WEEK = NVL(src_rec.ROLLING_WEEK,ROLLING_WEEK),
        LAST_PROD_DATE = NVL(src_rec.LAST_PROD_DATE,LAST_PROD_DATE),
        NO_OF_COIL = NVL(src_rec.NO_OF_COIL,NO_OF_COIL),
        DEVIDE_STATION = NVL(src_rec.DEVIDE_STATION,DEVIDE_STATION),
        CB_FIRST_ORDER_ITEM = NVL(src_rec.CB_FIRST_ORDER_ITEM,CB_FIRST_ORDER_ITEM),
        ORDER_WIDTH = NVL(src_rec.ORDER_WIDTH,ORDER_WIDTH),
        ORDER_THICK = NVL(src_rec.ORDER_THICK,ORDER_THICK),
        ORDER_IN_DIAM = NVL(src_rec.ORDER_IN_DIAM,ORDER_IN_DIAM),
        VENDOR_NO = NVL(src_rec.VENDOR_NO,VENDOR_NO),
        DEFACT01 = NVL(src_rec.DEFACT01,DEFACT01),
        DEFACT02 = NVL(src_rec.DEFACT02,DEFACT02),
        DEFACT03 = NVL(src_rec.DEFACT03,DEFACT03),
        DEFACT04 = NVL(src_rec.DEFACT04,DEFACT04),
        DEFACT05 = NVL(src_rec.DEFACT05,DEFACT05),
        DATE_LAST_MAINT = NVL(src_rec.DATE_LAST_MAINT,DATE_LAST_MAINT),
        TIME_LAST_MAINT = NVL(src_rec.TIME_LAST_MAINT,TIME_LAST_MAINT),
        PROG_LAST_MAINT = NVL(src_rec.PROG_LAST_MAINT,PROG_LAST_MAINT),
        USER_LAST_MAINT = NVL(src_rec.USER_LAST_MAINT,USER_LAST_MAINT),
        HEAT_NO = NVL(src_rec.HEAT_NO,HEAT_NO),
        SURFACE_QUALITY = NVL(src_rec.SURFACE_QUALITY,SURFACE_QUALITY),
        EDGING = NVL(src_rec.EDGING,EDGING),
        OEM_NO = NVL(src_rec.OEM_NO,OEM_NO),
        LINE_MARKING = NVL(src_rec.LINE_MARKING,LINE_MARKING),
        SLEEVE_KIND = NVL(src_rec.SLEEVE_KIND,SLEEVE_KIND),
        PAPER_CODE = NVL(src_rec.PAPER_CODE,PAPER_CODE),
        MOTHER_COIL_NO = NVL(src_rec.MOTHER_COIL_NO,MOTHER_COIL_NO),
        PREV_SCHD_NO = NVL(src_rec.PREV_SCHD_NO,PREV_SCHD_NO),
        OPER_CODE = NVL(src_rec.OPER_CODE,OPER_CODE),
        RUSH_ORDER = NVL(src_rec.RUSH_ORDER,RUSH_ORDER),
        COIL_APPLY = NVL(src_rec.COIL_APPLY,COIL_APPLY),
        CC_FLAG = NVL(src_rec.CC_FLAG,CC_FLAG),
        COIL_LENGTH = NVL(src_rec.COIL_LENGTH,COIL_LENGTH),
        PRODUCT_CODE = NVL(src_rec.PRODUCT_CODE,PRODUCT_CODE),
        QC_COMMENT = NVL(src_rec.QC_COMMENT,QC_COMMENT),
        FACTORY = NVL(src_rec.FACTORY,FACTORY),
        TOTAL_REDUCTION = NVL(src_rec.TOTAL_REDUCTION,TOTAL_REDUCTION),
        RESTRICT_APN = NVL(src_rec.RESTRICT_APN,RESTRICT_APN),
        FORECAST_DATE = NVL(src_rec.FORECAST_DATE,FORECAST_DATE),
        AVAILABLE = NVL(src_rec.AVAILABLE,AVAILABLE),
        SUB_COIL_WEIGHT = NVL(src_rec.SUB_COIL_WEIGHT,SUB_COIL_WEIGHT)
    WHERE COIL_NO = src_rec.coil_no
END FUNCTION